#!/bin/sh
# Resolve all dependencies that the application requires to run.

# Stop on errors
set -e

ROOT="$( cd "$( dirname "$(readlink -f "$0")" )/.." >/dev/null 2>&1 && pwd )"

cd "${ROOT}"

echo "Installing development dependencies..."
python3 -m pip install tox colorlog pre-commit $(grep mypy requirements-dev.txt)
