#!/bin/sh
# Setups the repository.

# Stop on errors
set -e

ROOT="$( cd "$( dirname "$(readlink -f "$0")" )/.." >/dev/null 2>&1 && pwd )"

cd "${ROOT}"
script/bootstrap

pre-commit install
pip3 install -r requirements-dev.txt

CONFIG=/run/user/$(id -u)/gvfs/smb-share:server=hassio,share=config/
if [ -d "$CONFIG" ] && [ ! -e dev-config ]; then
    ln -s "$CONFIG" dev-config
fi
